# Generated by Django 4.1.12 on 2023-10-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'api_job',
            },
        ),
    ]
